#!/usr/bin/env bash

MAIN_FILE=$1

add_message(){
  echo -e "\n" >> $1
  echo "%%% Local Variables: ***" >> $1
  echo "%%% mode:latex ***" >> $1
  echo "%%% TeX-master: \"$MAIN_FILE.tex\"  ***" >> $1
  echo "%%% End: ***" >> $1
}

[ -z "$MAIN_FILE" ] && MAIN_FILE="main"

for file in *.tex; do
  echo $file
  if ! grep -q "TeX-master: \"$MAIN_FILE.tex\"" "$file"; then
    add_message $file
  fi
done
